-- AlterTable
ALTER TABLE `activities` MODIFY `activityId` INTEGER NOT NULL AUTO_INCREMENT;

-- AlterTable
ALTER TABLE `assignments` MODIFY `assignmentId` INTEGER NOT NULL AUTO_INCREMENT;

-- AlterTable
ALTER TABLE `documents` ADD COLUMN `name` VARCHAR(255) NULL,
    MODIFY `docId` INTEGER NOT NULL AUTO_INCREMENT;

-- AlterTable
ALTER TABLE `users` MODIFY `userId` INTEGER NOT NULL AUTO_INCREMENT;
